name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: 'Features'
    labels:
      - 'feat'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: 'Documentation'
    labels:
      - 'docs'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'refactor'

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'

template: |
  ## What's Changed
  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
